apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: globex-app
    app.kubernetes.io/name: catalog-database
    app.kubernetes.io/part-of: globex-app
  name: inventory-app
